-- POPOLAMENTO PRODOTTO_ATTREZZATURA

INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5184572554', 'scala svedese', 50.33, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5616121125', 'tappetino fitness', 10.75, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5734168666', 'tavolo bar', 33.04, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5734168667', 'sedia bar', 13.04, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1002473331', 'panca', 36.56, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5189744043', 'tabellone', 142.24, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7819603166', 'canestro basket', 63.42, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1564812969', 'sedile tribuna', 38.66, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0027149555', 'porta calcetto', 50.02, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7035223416', 'pallone basket', 16.83, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5775275022', 'pallone calcetto', 11.77, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8603359912', 'divisa squadra basket', 16.58, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8586004022', 'divisa squadra calcetto', 18.2, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8603359913', 'borsone squadra basket', 16.58, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8586004023', 'borsone squadra calcetto', 18.2, NULL);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9744922467', 'Caviar - Salmon', 1.93, 5.76);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8127078013', 'Tequila - Sauza Silver', 4.5, 4.79);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9881529773', 'Ecolab - Medallion', 2.02, 5.56);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3540285966', 'Beans - Kidney, Canned', 4.17, 8.71);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5493464449', 'Cup - 4oz Translucent', 2.93, 7.34);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4912168396', 'Wine - Cahors Ac 2000, Clos', 1.26, 5.28);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1679802686', 'Lid - 10,12,16 Oz', 4.72, 6.75);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7466532744', 'Olives - Kalamata', 2.17, 7.48);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8961329850', 'Cheese - Brick With Pepper', 0.4, 0.76);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4697339145', 'Flour - Cake', 2.68, 8.7);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4647973843', 'Sage Derby', 3.67, 3.02);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1261743358', 'Garlic', 0.11, 2.23);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0056148250', 'Pepper - Black, Crushed', 3.21, 1.15);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6957247219', 'Kale - Red', 3.4, 5.11);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1667855834', 'Beer - Fruli', 0.98, 2.25);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5046638114', 'Energy - Boo - Koo', 0.96, 4.88);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7324261941', 'Longos - Grilled Veg Sandwiches', 3.16, 4.12);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0539388229', 'Cheese - Brick With Onion', 4.88, 8.79);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6113878373', 'Plasticforkblack', 4.59, 8.92);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6867834376', 'Lettuce - Green Leaf', 2.83, 9.47);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2247995796', 'Water - Evian 355 Ml', 4.52, 3.83);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1108756768', 'Bread - French Stick', 0.87, 7.73);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7732968889', 'Wine - Red Oakridge Merlot', 0.35, 6.27);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3251360061', 'Cookie Dough - Oatmeal Rasin', 2.65, 8.47);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6700348149', 'Mace', 1.26, 2.86);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1809498902', 'Sauce - Cranberry', 4.12, 2.54);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7163957461', 'Cookie Choc', 4.44, 8.6);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7072193598', 'Loaf Pan - 2 Lb, Foil', 0.91, 1.82);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6105477377', 'Bread - White, Unsliced', 2.7, 3.37);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5982365965', 'Bay Leaf Ground', 2.97, 9.07);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2322111859', 'Beans - Kidney, Canned', 1.82, 9.14);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7220212366', 'Lettuce - Iceberg', 2.83, 6.95);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9929032034', 'Brandy Cherry - Mcguinness', 4.3, 9.96);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2105029980', 'Apricots Fresh', 1.06, 5.83);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4100226330', 'Cookies - Fortune', 2.12, 6.13);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3074981568', 'Juice Peach Nectar', 2.36, 5.12);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4889537876', 'Pur Value', 2.23, 4.08);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7222210130', 'Muffin Orange Individual', 1.86, 3.9);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0675702471', 'Pear - Asian', 0.42, 5.76);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5516348160', 'Pork - European Side Bacon', 3.37, 6.1);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8954444529', 'Shrimp - Black Tiger 6 - 8', 4.71, 4.87);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2086421867', 'Rabbit - Frozen', 1.84, 9.45);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4492924103', 'Pork - Smoked Back Bacon', 3.59, 5.15);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9255332954', 'Chinese Foods - Chicken', 3.29, 2.59);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3422571230', 'Wine - Saint Emilion Calvet', 3.72, 9.59);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3781372681', 'Salmon - Sockeye Raw', 2.01, 2.37);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6737130182', 'Spice - Peppercorn Melange', 4.23, 5.31);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0221283215', 'Chinese Foods - Chicken Wing', 0.4, 3.27);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2644068668', 'Devonshire Cream', 3.21, 4.84);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3574906044', 'Curry Paste - Green Masala', 3.12, 1.71);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5670165817', 'Soup Campbells - Tomato Bisque', 4.03, 8.41);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4518810352', 'Pickles - Gherkins', 0.2, 4.4);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9979747282', 'Wine - Kwv Chenin Blanc South', 4.78, 3.12);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9766176172', 'Mushroom - Morel Frozen', 1.34, 2.29);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9803386699', 'Vaccum Bag 10x13', 2.35, 1.11);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1093329176', 'The Pop Shoppe - Lime Rickey', 2.62, 5.44);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3010465288', 'Daves Island Stinger', 3.48, 2.73);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5113639120', 'Pepper - Black, Ground', 1.29, 1.92);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3896542953', 'Beef - Tongue, Cooked', 0.68, 3.15);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0012459245', 'Water - Spring Water, 355 Ml', 3.89, 8.57);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4755391358', 'Bandage - Flexible Neon', 2.53, 1.94);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8999374580', 'Pastry - Trippleberry Muffin - Mini', 4.79, 3.16);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4204182439', 'Wine - White, Lindemans Bin 95', 0.49, 8.19);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8398042351', 'Cookie Dough - Chocolate Chip', 1.51, 5.96);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3976397678', 'Miso Paste White', 3.85, 2.38);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1427136722', 'Broom - Push', 4.54, 6.76);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1017419837', 'Lettuce - Mini Greens, Whole', 4.68, 8.28);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8389319285', 'Tabasco Sauce, 2 Oz', 3.95, 2.01);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3675453417', 'Tea - Mint', 4.22, 6.39);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8410844025', 'Chestnuts - Whole,canned', 1.0, 9.89);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4145092820', 'Cookies - Englishbay Wht', 3.37, 6.32);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9648589120', 'Artichoke - Fresh', 0.62, 7.54);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8317983568', 'Tea - Lemon Scented', 4.07, 2.96);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5099504610', 'Doilies - 8, Paper', 3.04, 8.77);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6215779754', 'Apron', 1.68, 5.65);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('1610338513', 'Fiddlehead - Frozen', 3.13, 5.16);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9783954560', 'Kumquat', 3.27, 2.64);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0368261113', 'Cheese - Colby', 2.59, 0.66);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8281571368', 'Ginger - Crystalized', 3.02, 7.75);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4837142414', 'Dc - Frozen Momji', 3.54, 4.26);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('8404444842', 'Kale - Red', 3.1, 1.81);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('9903976190', 'Mortadella', 0.3, 5.57);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6334613044', 'Sultanas', 1.72, 4.55);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2281431929', 'Soap - Hand Soap', 0.72, 0.82);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5035630371', 'Juice - Lagoon Mango', 1.21, 1.46);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5555975470', 'Vodka - Moskovskaya', 4.77, 3.31);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7499938906', 'Cheese - Brick With Pepper', 3.54, 4.78);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5160276869', 'Pie Box - Cello Window 2.5', 0.11, 8.05);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7710548912', 'Bay Leaf', 1.3, 4.19);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3436750147', 'Bread - Rolls, Rye', 1.45, 2.98);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('6848128667', 'Bagel - Everything', 0.55, 4.02);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4951191837', 'Soup - Campbells Mac N Cheese', 0.82, 2.95);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5373049315', 'Raisin - Dark', 4.81, 1.97);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5249050757', 'Bread - English Muffin', 2.32, 0.53);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('7146829497', 'Stainless Steel Cleaner Vision', 4.99, 0.82);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('3824181329', 'Pepper - Sorrano', 3.2, 7.01);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('4050834554', 'Shrimp - Black Tiger 8 - 12', 3.55, 7.12);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('5807028391', 'Melon - Watermelon Yellow', 4.3, 2.65);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('2630971287', 'Shrimp - Black Tiger 13/15', 3.33, 5.26);
INSERT INTO prodotto_attrezzatura (codice_barre, nome_prodotto, costo_unitario, prezzo_vendita_unitario) VALUES ('0946243893', 'Placemat - Scallop, White', 0.81, 1.15);
