-- POPOLAMENTO PERSONA

INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('EVQXXV35O88Z845F', 'Vivyan', 'Tucsell', 'Xingfu', TO_DATE('24/06/1992', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('PPXWDU31I04B263C', 'Juieta', 'Bernardino', 'Sorinomo', TO_DATE('20/12/1947', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('PYPODQ34D32C117F', 'Randee', 'Salomon', 'Qizili', TO_DATE('04/04/1951', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NTSRUC90H06I924Y', 'Andy', 'Blackhurst', 'Nanxing', TO_DATE('30/12/1960', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('EPDJQO69D06Z640H', 'Reinhard', 'Dedmam', 'København', TO_DATE('17/02/1974', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('OSBTTP08I81O197K', 'Nathalie', 'Bolens', 'Hroznětín', TO_DATE('10/08/1993', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('KPPRTH66L84J377O', 'Morena', 'Drayton', 'Dulyapino', TO_DATE('02/08/2000', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('PKXSMJ51K19P701U', 'Ernest', 'Abarough', 'Rosh Pinna', TO_DATE('29/09/2008', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CPALLK07D82R196H', 'Orelie', 'Belson', 'Dundee', TO_DATE('27/02/1970', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WGLZTK42G48Y967X', 'Ingmar', 'Bouda', 'Asíni', TO_DATE('02/02/1942', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CGIUJV94K42C915D', 'Val', 'Gillbanks', 'Dallas', TO_DATE('17/08/1950', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('JXQYCE43W47S283H', 'Barbi', 'Minot', 'Gaopi', TO_DATE('01/08/1958', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('EFYYUI98M60M985I', 'Codi', 'Aitchinson', 'Panambi', TO_DATE('29/07/2003', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('SXAZNH21T96D805U', 'Ronni', 'Isworth', 'Kadugannawa', TO_DATE('13/03/1962', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HCKYHW00M78W508U', 'Richard', 'McEntee', 'Hovd', TO_DATE('19/08/1971', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WXIGWA03J07T275J', 'Marylynne', 'Heims', 'Upi', TO_DATE('23/07/1983', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NJCJKE60D13O802G', 'Robbin', 'Basnall', 'Astghadzor', TO_DATE('11/09/1979', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HXWLZA07N98T897X', 'Roman', 'Guslon', 'Fenyan', TO_DATE('31/10/1985', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('DSHSRL32Q69A666R', 'Romy', 'Vaskov', 'Aqaba', TO_DATE('13/12/1989', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('KXLGXC56Y75P629J', 'Sam', 'Harsnipe', 'Esperanza', TO_DATE('04/10/1963', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('UZGMWH06O34B499Q', 'Karie', 'Croke', 'Arys', TO_DATE('06/08/1956', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NGMLDP73Z18B213P', 'Deanne', 'Tempest', 'Kishi', TO_DATE('02/01/1946', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NMYMCN76J64E546E', 'Toma', 'Swenson', 'Karangpao', TO_DATE('13/02/1954', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('ANJUPQ16N94O866V', 'Ninon', 'Capps', 'Medvezh’yegorsk', TO_DATE('29/09/1953', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('JIIDPP31D48C768V', 'Gaylor', 'Drust', 'Sancha', TO_DATE('12/09/2012', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('YSIJRN93P10W354N', 'Brooke', 'Ilbert', 'Longxing', TO_DATE('04/09/1964', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('XEPAET02D16P616W', 'Annis', 'Labbey', 'Birao', TO_DATE('28/04/1962', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('KKYZOZ13S02D997F', 'Marv', 'Tenniswood', 'Zhujiang', TO_DATE('25/09/1949', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('GPVATN29S13Y054D', 'Melitta', 'Connerly', 'Dimitrov', TO_DATE('24/06/1970', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('GVJHAU27Q32N837Y', 'Mavis', 'Simonato', 'East End', TO_DATE('29/03/1974', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('POPHNI24H58I638T', 'Nolly', 'Dashwood', 'Banjar Tengah', TO_DATE('08/05/1991', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WSHZIH31Z44T659K', 'Yolanthe', 'Murrhardt', 'Solina', TO_DATE('11/09/1967', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('MWYJND99N34E339N', 'Delmer', 'Ortiger', 'Chicago', TO_DATE('02/06/2013', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('LXCNXU89A74R004E', 'Malvina', 'Spera', 'Santa Vitória do Palmar', TO_DATE('02/12/2001', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('FMGUGO85F46L561A', 'Carolyn', 'Standon', 'Las Toscas', TO_DATE('06/02/1951', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('ZEYICX55K63G324J', 'Hermie', 'Mordecai', 'MacArthur', TO_DATE('21/10/1983', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('PZHJMF24E99L313C', 'Addison', 'Flockhart', 'Dvinskoy', TO_DATE('22/09/1987', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('SGBPQH53A05S586C', 'Marjie', 'Workman', 'Rouen', TO_DATE('05/07/2005', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('JHOPPU29Z77M163J', 'Marissa', 'Birney', 'Hukeng', TO_DATE('07/02/1986', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('ZBBDEU77D55I302K', 'Saba', 'Berlin', 'Soledad', TO_DATE('17/06/1977', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WSJCQY00A64N338W', 'Hammad', 'Neubigin', 'Shigu', TO_DATE('09/11/1980', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('AOXAGG69B07A485B', 'Gerrard', 'Folke', 'Usab', TO_DATE('25/11/1956', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('DHLVWH67F48L089B', 'Robinetta', 'Studde', 'Jāwā', TO_DATE('06/08/1999', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('KOFYYT17S38U638U', 'Nickolas', 'Borge', 'Pilníkov', TO_DATE('03/02/1949', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('AUKCOJ30U31I516E', 'Leroi', 'Symon', 'Boyle', TO_DATE('26/10/1985', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('MJWBIH85E68R689T', 'Merry', 'Klemenz', 'Padangan', TO_DATE('06/07/1978', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('ALAPYD31J47A233B', 'Clerc', 'Bellam', 'Hutag', TO_DATE('14/10/2001', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('OKEASQ06Q16N152Y', 'Jeanette', 'Hallad', 'Pilar', TO_DATE('20/01/1955', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WTXBDU76L84N548F', 'Candida', 'Frotton', 'Esperantina', TO_DATE('02/06/2006', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WFGGVJ49G16Z340K', 'Janaya', 'Rameau', 'Szczerców', TO_DATE('16/10/1990', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HOZKHB25M69L179W', 'Mandi', 'Bernocchi', 'La Asunción', TO_DATE('23/03/1962', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('RHQFLP10T16X021O', 'Mel', 'Altofts', 'Saint John’s', TO_DATE('12/02/1992', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CJZEPY64B84J850T', 'Doralynne', 'McGrann', 'Daguma', TO_DATE('21/07/1949', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('VYCSDG06O09L210T', 'Tomkin', 'Tomaszkiewicz', 'Kista', TO_DATE('17/01/1970', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('QBBCDM03T20J223R', 'Jock', 'Hyde', 'Rustam jo Goth', TO_DATE('13/09/1997', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('IHRQMO72J49T372C', 'Quint', 'Auger', 'Vila Nova', TO_DATE('20/09/1970', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('LERWYJ44P62H466Y', 'Peyton', 'Sargerson', 'Pieńsk', TO_DATE('17/01/2005', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('UDJISE18C58B844F', 'Giulietta', 'Martinovic', 'Khvatovka', TO_DATE('19/04/1980', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('QXZUTJ60Y63J106D', 'Nikolaos', 'Thomen', 'Ternopil’', TO_DATE('23/08/2008', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('UBGRPY47S28M371N', 'Eula', 'Peck', 'Romanovskaya', TO_DATE('21/10/1950', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('RCGFDE26R91D472V', 'Wright', 'Kingsworth', 'Philipsburg', TO_DATE('20/01/2013', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HTOLJO06B26T598N', 'Rina', 'Slainey', 'Dokolo', TO_DATE('07/06/1961', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('PYYJZM70U78S551D', 'Fergus', 'Stickel', 'Daze', TO_DATE('26/06/1959', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('XUWECR40J59J366M', 'Jessamyn', 'Insole', 'Jasienica Rosielna', TO_DATE('17/05/2011', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('WONDHG91B60R291V', 'Linea', 'Hitschke', 'Mujur', TO_DATE('02/08/1976', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('JKYKSM74N83S975Q', 'Glyn', 'Devonshire', 'Antony', TO_DATE('07/04/2012', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('MVQPMG17O50Z911K', 'Emilio', 'Harget', 'Situbondo', TO_DATE('01/09/1999', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('EIYXNK22K73E455A', 'Koressa', 'Lannin', 'Tosu', TO_DATE('02/11/1977', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('FNLXLL57Q47Y194U', 'Simonne', 'Lindmark', 'Évry', TO_DATE('14/09/1943', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('KDTTCD26U39W036E', 'Mariele', 'MacKaig', 'Marićka', TO_DATE('16/12/1942', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('VUJQMZ75L68W541R', 'Andonis', 'Pentecost', 'Lubei', TO_DATE('09/09/2005', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('IKPYMQ51F96Y769N', 'Eddi', 'Franzman', 'Czerwieńsk', TO_DATE('23/11/1961', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NZSJLB89D87V456Y', 'Cherry', 'Shipston', 'Sillon', TO_DATE('10/04/1960', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HXHZJE80P66S207J', 'Chelsea', 'Longfield', 'Nanganumba', TO_DATE('03/07/1958', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('YGRELE13R74E539B', 'Chelsae', 'Pinckstone', 'Águas', TO_DATE('08/10/1942', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('MACPOG67H92G694Y', 'Ardene', 'Blant', 'Huizhai', TO_DATE('05/08/1960', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NVYNAI56L52L407G', 'Marion', 'Wollrauch', 'Basak', TO_DATE('05/01/1968', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HTXITV20A02P731J', 'Shelby', 'Horley', 'Candelária', TO_DATE('20/02/1975', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CFHERB65N79Y741N', 'Atlanta', 'Punshon', 'Fiditi', TO_DATE('27/02/1973', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('YYSAOA37L17T806M', 'Jarid', 'Westwell', 'Kurashiki', TO_DATE('04/07/1978', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('YFCMBR38O73W977Z', 'Honey', 'Springthorp', 'Yashan', TO_DATE('13/04/1994', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('VCHGSK89E29G238D', 'Bambi', 'Giorgeschi', 'Yerazgavors', TO_DATE('06/03/1942', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('LHDWMA91Y89R464L', 'Rose', 'Wardingly', 'Houston', TO_DATE('07/12/1947', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('LGRQSR76I22X607Q', 'Nahum', 'MacHarg', 'Severka', TO_DATE('27/09/1994', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('EIVKNT21K28N459I', 'Elset', 'Rumgay', 'Svrljig', TO_DATE('11/04/1968', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('TMVXBS08H38M345H', 'Uta', 'Birkenhead', 'Kladi', TO_DATE('12/02/1951', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('NLHIXB62S32Y775K', 'Corabelle', 'Tutchell', 'Kanashevo', TO_DATE('21/03/1957', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('APRRPJ58E87T744L', 'Jehanna', 'Alvarez', 'Xi’an', TO_DATE('11/12/1954', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('OVPLCL34Y26D665P', 'Wyn', 'Gusney', 'Talayan', TO_DATE('21/04/1973', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('IGWSSK77H62B335M', 'Dirk', 'O''Dwyer', 'Angelochóri', TO_DATE('14/07/1984', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('OQTAQU05E57V730V', 'Kissiah', 'Hamblyn', 'Pingli', TO_DATE('06/08/2013', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CAKZQH40R12B796K', 'Giustino', 'Nathan', 'Khong', TO_DATE('15/12/1946', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CXMUXZ37F54O205W', 'Clarabelle', 'Kegley', 'Clearwater', TO_DATE('18/04/1971', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('XQILFH60T93K325T', 'Corliss', 'Ianitti', 'San Agustín de Valle Fértil', TO_DATE('28/07/2007', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CWTUIO18G87D467T', 'Tracie', 'Fibben', 'Palmdale', TO_DATE('25/07/1995', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('YVQNLG13Y95L654M', 'Ricardo', 'Budgen', 'Şabāḩ as Sālim', TO_DATE('30/12/1994', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('OAKPXU74Z99Z833W', 'Jo ann', 'Brandts', 'Tosno', TO_DATE('17/11/1945', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('CQQCZH02S50F780Q', 'Felicia', 'Lowin', 'Carpalho', TO_DATE('28/06/1946', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('HJEMQE85I87J391B', 'Fanchette', 'Wadwell', 'Sadská', TO_DATE('21/02/1997', 'dd/mm/yyyy'));
INSERT INTO persona (cf, nome, cognome, luogo_nascita, data_nascita) VALUES ('JVQHUH92Y54K000O', 'Desi', 'Kruszelnicki', 'Cimo de Vila', TO_DATE('19/04/2011', 'dd/mm/yyyy'));